name: Prize Pig Productions
favicon: null
layout_spectrum: 0.37127
typography_spectrum: 0.39034
title: Prize Pig Productions
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#0093dd'
    - '#3f4447'
    - '#5ab7e3'
    - '#afb0b2'
  brandStrength: 0.24030484608374536
  lightness: 0.7966677609365433
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
